### PR TITLE
Set default TTS settings and add build script for Windows

### PR DESCRIPTION
**Pull request by bouchaala-sabri**
This PR sets the default TTS language to en-US and the default TTS voice to en-us-x-tpc-network for personal use. The network voice provides better quality than the offline voice. It also adds a new script for building the release on Windows.

Changes made:
- Set default TTS language to en-US
- Set default TTS voice to en-us-x-tpc-network
- Add buildReleaseWin script for Windows users

The changes to the TTS settings were made for personal use, as the network voice provides better quality than the offline voice. The new buildReleaseWin script allows Windows users to easily build the release version of the app.

### CODE REVIEW

**Comment by nyagami** [comment]
But... there're users who dont read LN in English (included me)

**Comment by bouchaala-sabri** [comment]
of course I'm aware of that, in fact, I can read Arabic and French my self
but as I mentioned in the PR, I made these changes for my own selfish
personal needs. 😄

In all seriousness, I had never developed anything for mobile or Android
before. It took me two days just to figure out how to build the project.
But it was worth it for me because the neural network voices are much
better. In fact, the offline voice was so irritating that I couldn't stand
to listen to it.

I decided to share this in case someone else needed it. And if there's
anyone who can add a setting to choose the language and voices, that would
be great.

I also tried to highlight the sentence being read and make the scroll
follow the current sentence, but I wasn't able to do that.

**Comment by cd0rw0** [comment]
Hai, 

thanks for the this PR. i total agree, offline voice is terrible. 
im really looking forward for this.

**Comment by nyagami** [comment]
Everything you want is available in latest code

**Comment by rajarsheechatterjee** [comment]
Closing this as the features are now available in the `master` branch.

**Pull request closed without merging**
