### PR TITLE
fix search error when query contains '

### PR DESCRIPTION
**Pull request by Anan5a**
Refer the images https://postimg.cc/gallery/kRWdwjY

### CODE REVIEW

**Comment by rajarsheechatterjee** [comment]
@Anan5a Could you run prettier to pass the PR check?

**Comment by Anan5a** [comment]
> @Anan5a Could you run prettier to pass the PR check?

I'll try

**Comment by Anan5a** [comment]
> @Anan5a Could you run prettier to pass the PR check?

I ended up with this while setting up for prettier

**Comment by Anan5a** [comment]
> @Anan5a Could you run prettier to pass the PR check?

Done. But 52 files changed !?

**Comment by rajarsheechatterjee** [comment]
> Done. But 52 files changed !?

You would have to rebase your PR, that should remove those changes.

**Pull request closed without merging**
