### PR TITLE
Enhancement: Make swiping of plugins/sources less sensitive

### PR DESCRIPTION
**Pull request by Skeltons**
Make swiping source/plugins less sensitive, related issue #1199 

https://github.com/user-attachments/assets/de4136f1-1b25-4f5f-b869-43b1befae593

### CODE REVIEW

**Review by rajarsheechatterjee — APPROVED** [review]

**Comment by Palloxin** [comment]
https://github.com/LNReader/lnreader/issues/1199
this would help too

**Comment by Palloxin** [comment]
Btw 62 is too much. It's cranky now. Can u try 40?

**Comment by Skeltons** [comment]
I have tried 50 and it was still triggering the swipe, i think this would be quite hard to balance

**Comment by Palloxin** [comment]
In ny opinion it's enough to lower the sensivity to 30-40 reducing the issue until a 30° angle thresold is implemented

**Comment by Skeltons** [comment]
It is currently hard coded but the best way is probably to turn it into a function of your phone's width

**Comment by Skeltons** [comment]
If you dont mind can i have your phone model

**Comment by rajarsheechatterjee** [comment]
In my opinion, we shouldn't adjust its value based on lower-end or older devices. If it's working well for most devices, that's sufficient. He uses a Huawei P8 Lite 2017.

**Comment by Palloxin** [comment]
My device is very smooth when using plugin cards, it's not due to that.

**Comment by Skeltons** [comment]
> My device is very smooth when using plugin cards, it's not due to that because there is no lag, surprisingly.

Ah its a misunderstanding i wanted to know your device so i can get the width and find a correlation

**Comment by Palloxin** [comment]
1080x1920. Maybe a % value would be better?

**Comment by CheshireCat27** [comment]
Tested on a Moto One 5G Ace, was able to get minor hitching when installing plugins, but nothing else.

**Comment by CheshireCat27** [comment]
I have a painfully slow tablet I can test on as well if it would be helpful.  However it barely runs a handful of Firefox tabs so I wouldn't say its indicative of the average low end device.

**Comment by Palloxin** [comment]
Here is my data, I used an autoclicked with precise coordinates, Macrorify.
-720x1280 (I changed it through settings)
-speed: 20

Value 35 (minimum non-responsive width: 65px)

https://github.com/user-attachments/assets/847b1b55-92ea-469c-8926-c7bbef435916

Value 62 (minimum non-responsive width: 115px)

https://github.com/user-attachments/assets/224b558c-4a34-437b-b735-2eba36a15efe

**Comment by Palloxin** [comment]
Practical test videos:
Value: 30
Comfortable, no unwanted trigger

https://github.com/user-attachments/assets/3adea854-c765-4ee5-8f6b-604e68a244e0

Value 25
Some unwanted trigger start to appear. 30 os better.

https://github.com/user-attachments/assets/424b6a04-596e-4183-b7a5-4fd295bc6fb1

**Comment by Palloxin** [comment]
The default value was 10(before this commit). Three times it reduces the problems by 90%.
Stopping completely unwanted triggers comes with the price of cranky plugin cards.
It's better to just reduce them.

**Comment by Skeltons** [comment]
Ok that sounds like a good compromise, pretty unrealistic to expect no triggers

**Pull request merged**
