### PR TITLE
fix search error when query contains '

### PR DESCRIPTION
**Pull request by Anan5a**
It's a long story...

It started with #496 then #844

Since it was not merged with #844 a long time has passed. And the repository structure changed. And thanks to github it was kinda impossible to responsibly create a PR without some old commits for some reason.

I hope @rajarsheechatterjee will merge it this time

### CODE REVIEW

**Comment by nyagami** [comment]
Can it work with \' ?

**Comment by Anan5a** [comment]
> Can it work with `\'` ?

No, are you going to type `\'` when searching for a novel? Then we might just move to proper SQL injection measures, like prepared statements

**Review by rajarsheechatterjee — APPROVED** [review]

**Comment by rajarsheechatterjee** [comment]
@Anan5a Have you tested the change? It doesn't seem to be working.

```bash
ERROR  near "Test": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT *
  FROM
  (
    SELECT NIL.*, chaptersUnread, chaptersDownloaded, lastReadAt, lastUpdatedAt
    FROM 
    (
      SELECT 
        Novel.*,
        category,
        categoryId
      FROM
      Novel LEFT JOIN (
        SELECT NovelId, name as category, categoryId FROM (NovelCategory JOIN Category ON NovelCategory.categoryId = Category.id)
      ) as NC ON Novel.id = NC.novelId
      WHERE inLibrary = 1
    ) as NIL 
    LEFT JOIN 
    (
      SELECT 
        SUM(unread) as chaptersUnread, SUM(isDownloaded) as chaptersDownloaded, 
        novelId, MAX(readTime) as lastReadAt, MAX(updatedTime) as lastUpdatedAt
      FROM Chapter
      GROUP BY novelId
    ) as C ON NIL.id = C.novelId
  ) WHERE 1 = 1 
 AND name LIKE '%Test\' Test%'  ORDER BY id DESC
```

**Comment by Anan5a** [comment]
hmm... I'll do more testing, this should've worked.

On second thought it seems the expo library has support for prepared statements, so might as well move there instead of hot fixing things.

**Comment by Anan5a** [comment]
@rajarsheechatterjee I have updated the search function to use prepared statement, It should work now with any input

**Comment by Anan5a** [comment]
@rajarsheechatterjee lint error on unrelated files?

**Comment by rajarsheechatterjee** [comment]
> @rajarsheechatterjee lint error on unrelated files?

It appears to be in your changes.

```shell
/home/runner/work/lnreader/lnreader/src/database/queries/LibraryQueries.ts
   99:56  error    Insert `;`                    prettier/prettier
   99:56  warning  Missing semicolon             semi
  109:14  warning  Strings must use singlequote  quotes
  110:45  error    Insert `;`                    prettier/prettier
  110:45  warning  Missing semicolon             semi
```

**Comment by Anan5a** [comment]
> > @rajarsheechatterjee lint error on unrelated files?
> 
> It appears to be in your changes.
> 
> ```shell
> /home/runner/work/lnreader/lnreader/src/database/queries/LibraryQueries.ts
>    99:56  error    Insert `;`                    prettier/prettier
>    99:56  warning  Missing semicolon             semi
>   109:14  warning  Strings must use singlequote  quotes
>   110:45  error    Insert `;`                    prettier/prettier
>   110:45  warning  Missing semicolon             semi
> ```

updated, for some reason vscode didn't give any warning about the semicolons

**Pull request merged**
