### PR TITLE
link fixing

### LINKED ISSUE #1298: There are no illustrations for downloaded chapters
### Steps to reproduce

When downloading a chapter from ranobelib (I didn’t check others, because I don’t use them, maybe there is a problem on others too), when opening the downloaded chapter there are no illustrations, the problem appeared on version r1016, while on r1015 the chapters download normally with illustrations.

Here is an example from DxD chapter 220
изображение_2024-10-30_232603739
изображение_2024-10-30_232529567

### Expected behavior

Must swing illustrations

### Actual behavior

No illustrations

### LNReader version

2.0.0

### Android version

Android 10

### Device

Realme C11 (2020)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Rider21**
closes #1298

### CODE REVIEW

**Comment by nyagami** [comment]
doest eact-native-url-polyfill work?

**Comment by nyagami** [comment]
I think urlencode is still helpful for some sites using uncommon encoding

**Comment by Rider21** [comment]
I think `fetchText` with [`FileReader`](
https://github.com/facebook/react-native/blob/v0.72.2/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/blob/FileReaderModule.java#L55) will suffice.
And the rest can be hardcoded into plugins if needed

**Comment by nyagami** [comment]
No, in case of shu69 (if i remember correctly), we have to encode the search param

**Comment by Rider21** [comment]
Can't we pre-encode the text in the desired encoding?
Why encode the same data all the time.
[Code](https://github.com/LNReader/lnreader-plugins/blob/5a6adb7676366379d76a3cbfe784936858c37242/src/plugins/chinese/69xinshu.ts#L152)

**Review by nyagami — APPROVED** [review]

**Pull request merged**
